---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-users
  name: mysql-users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql-users
  template:
    metadata:
      labels:
        app: mysql-users
    spec:
      containers:
      - image: localhost:5000/mysql-users:v1
        imagePullPolicy: Always
        name: mysql-users
        readinessProbe:
          tcpSocket:
            port: 8086
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8086
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-users
  name: mysql-users
spec:
  type: NodePort
  ports:
  - name: http
    port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: mysql-users

